# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1194, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.verticalTabWidget.setObjectName("verticalTabWidget")
        self.Video = QtWidgets.QWidget()
        self.Video.setObjectName("Video")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Video)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.Video)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.imagePreview = QtWidgets.QLabel(self.frame)
        self.imagePreview.setText("")
        self.imagePreview.setObjectName("imagePreview")
        self.verticalLayout_6.addWidget(self.imagePreview)
        self.imageSpacerFrame = QtWidgets.QFrame(self.frame)
        self.imageSpacerFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imageSpacerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageSpacerFrame.setLineWidth(0)
        self.imageSpacerFrame.setObjectName("imageSpacerFrame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.imageSpacerFrame)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.imageFormLayout = QtWidgets.QFormLayout()
        self.imageFormLayout.setObjectName("imageFormLayout")
        self.verticalLayout_11.addLayout(self.imageFormLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.imageSpacerFrame)
        self.centerLabel = QtWidgets.QLabel(self.frame)
        self.centerLabel.setText("")
        self.centerLabel.setObjectName("centerLabel")
        self.verticalLayout_6.addWidget(self.centerLabel)
        self.centerLabel.raise_()
        self.imagePreview.raise_()
        self.imageSpacerFrame.raise_()
        self.horizontalLayout_3.addWidget(self.frame)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.logsPreview = QtWidgets.QTextEdit(self.Video)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logsPreview.setFont(font)
        self.logsPreview.setReadOnly(True)
        self.logsPreview.setObjectName("logsPreview")
        self.verticalLayout_8.addWidget(self.logsPreview)
        self.QueueListWidget = QtWidgets.QListWidget(self.Video)
        self.QueueListWidget.setObjectName("QueueListWidget")
        self.verticalLayout_8.addWidget(self.QueueListWidget)
        self.QueueButton = QtWidgets.QPushButton(self.Video)
        self.QueueButton.setObjectName("QueueButton")
        self.verticalLayout_8.addWidget(self.QueueButton)
        self.RifePause = QtWidgets.QPushButton(self.Video)
        self.RifePause.setObjectName("RifePause")
        self.verticalLayout_8.addWidget(self.RifePause)
        self.RifeResume = QtWidgets.QPushButton(self.Video)
        self.RifeResume.setObjectName("RifeResume")
        self.verticalLayout_8.addWidget(self.RifeResume)
        self.processedPreview = QtWidgets.QLabel(self.Video)
        self.processedPreview.setObjectName("processedPreview")
        self.verticalLayout_8.addWidget(self.processedPreview)
        self.ETAPreview = QtWidgets.QLabel(self.Video)
        self.ETAPreview.setObjectName("ETAPreview")
        self.verticalLayout_8.addWidget(self.ETAPreview)
        self.FPSPreview = QtWidgets.QLabel(self.Video)
        self.FPSPreview.setObjectName("FPSPreview")
        self.verticalLayout_8.addWidget(self.FPSPreview)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.RifeStart = QtWidgets.QPushButton(self.Video)
        self.RifeStart.setObjectName("RifeStart")
        self.verticalLayout_4.addWidget(self.RifeStart)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Input_video_rife = QtWidgets.QPushButton(self.Video)
        self.Input_video_rife.setObjectName("Input_video_rife")
        self.horizontalLayout_4.addWidget(self.Input_video_rife)
        self.Input_video_rife_url = QtWidgets.QPushButton(self.Video)
        self.Input_video_rife_url.setObjectName("Input_video_rife_url")
        self.horizontalLayout_4.addWidget(self.Input_video_rife_url)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.Output_folder_rife = QtWidgets.QPushButton(self.Video)
        self.Output_folder_rife.setMinimumSize(QtCore.QSize(0, 0))
        self.Output_folder_rife.setObjectName("Output_folder_rife")
        self.verticalLayout_4.addWidget(self.Output_folder_rife)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.Video)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.AICombo = QtWidgets.QComboBox(self.Video)
        self.AICombo.setObjectName("AICombo")
        self.horizontalLayout_5.addWidget(self.AICombo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.Video)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.Rife_Model = QtWidgets.QComboBox(self.Video)
        self.Rife_Model.setObjectName("Rife_Model")
        self.horizontalLayout_6.addWidget(self.Rife_Model)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.Video)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.Rife_Times = QtWidgets.QComboBox(self.Video)
        self.Rife_Times.setMinimumSize(QtCore.QSize(0, 0))
        self.Rife_Times.setObjectName("Rife_Times")
        self.Rife_Times.addItem("")
        self.Rife_Times.addItem("")
        self.Rife_Times.addItem("")
        self.horizontalLayout_7.addWidget(self.Rife_Times)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.denoiseLevelLabel = QtWidgets.QLabel(self.Video)
        self.denoiseLevelLabel.setObjectName("denoiseLevelLabel")
        self.horizontalLayout_8.addWidget(self.denoiseLevelLabel)
        self.denoiseLevelSpinBox = QtWidgets.QSpinBox(self.Video)
        self.denoiseLevelSpinBox.setMinimum(0)
        self.denoiseLevelSpinBox.setMaximum(3)
        self.denoiseLevelSpinBox.setObjectName("denoiseLevelSpinBox")
        self.horizontalLayout_8.addWidget(self.denoiseLevelSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.RifePB = QtWidgets.QProgressBar(self.Video)
        self.RifePB.setProperty("value", 0)
        self.RifePB.setObjectName("RifePB")
        self.verticalLayout.addWidget(self.RifePB)
        self.verticalTabWidget.addTab(self.Video, "")
        self.Image = QtWidgets.QWidget()
        self.Image.setObjectName("Image")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.Image)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_2 = QtWidgets.QFrame(self.Image)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.imagePreview_2 = QtWidgets.QLabel(self.frame_2)
        self.imagePreview_2.setText("")
        self.imagePreview_2.setObjectName("imagePreview_2")
        self.verticalLayout_7.addWidget(self.imagePreview_2)
        self.imageSpacerFrame_2 = QtWidgets.QFrame(self.frame_2)
        self.imageSpacerFrame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imageSpacerFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageSpacerFrame_2.setLineWidth(0)
        self.imageSpacerFrame_2.setObjectName("imageSpacerFrame_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.imageSpacerFrame_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.imageFormLayout_2 = QtWidgets.QFormLayout()
        self.imageFormLayout_2.setObjectName("imageFormLayout_2")
        self.verticalLayout_12.addLayout(self.imageFormLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_12.addItem(spacerItem1)
        self.verticalLayout_7.addWidget(self.imageSpacerFrame_2)
        self.centerLabel_2 = QtWidgets.QLabel(self.frame_2)
        self.centerLabel_2.setText("")
        self.centerLabel_2.setObjectName("centerLabel_2")
        self.verticalLayout_7.addWidget(self.centerLabel_2)
        self.horizontalLayout_9.addWidget(self.frame_2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.logsPreview_2 = QtWidgets.QTextEdit(self.Image)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logsPreview_2.setFont(font)
        self.logsPreview_2.setReadOnly(True)
        self.logsPreview_2.setObjectName("logsPreview_2")
        self.verticalLayout_10.addWidget(self.logsPreview_2)
        self.RESPreview = QtWidgets.QLabel(self.Image)
        self.RESPreview.setObjectName("RESPreview")
        self.verticalLayout_10.addWidget(self.RESPreview)
        self.horizontalLayout_10.addLayout(self.verticalLayout_10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.RifeStart_2 = QtWidgets.QPushButton(self.Image)
        self.RifeStart_2.setObjectName("RifeStart_2")
        self.verticalLayout_13.addWidget(self.RifeStart_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Input_Image = QtWidgets.QPushButton(self.Image)
        self.Input_Image.setObjectName("Input_Image")
        self.horizontalLayout_12.addWidget(self.Input_Image)
        self.Input_video_rife_url_2 = QtWidgets.QPushButton(self.Image)
        self.Input_video_rife_url_2.setObjectName("Input_video_rife_url_2")
        self.horizontalLayout_12.addWidget(self.Input_video_rife_url_2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.Output_folder_rife_2 = QtWidgets.QPushButton(self.Image)
        self.Output_folder_rife_2.setMinimumSize(QtCore.QSize(0, 0))
        self.Output_folder_rife_2.setObjectName("Output_folder_rife_2")
        self.verticalLayout_13.addWidget(self.Output_folder_rife_2)
        self.horizontalLayout_11.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_15 = QtWidgets.QLabel(self.Image)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        self.AICombo_Image = QtWidgets.QComboBox(self.Image)
        self.AICombo_Image.setObjectName("AICombo_Image")
        self.horizontalLayout_13.addWidget(self.AICombo_Image)
        self.verticalLayout_14.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_16 = QtWidgets.QLabel(self.Image)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16)
        self.ModelCombo_Image = QtWidgets.QComboBox(self.Image)
        self.ModelCombo_Image.setObjectName("ModelCombo_Image")
        self.horizontalLayout_14.addWidget(self.ModelCombo_Image)
        self.verticalLayout_14.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_17 = QtWidgets.QLabel(self.Image)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_15.addWidget(self.label_17)
        self.Times_Image = QtWidgets.QComboBox(self.Image)
        self.Times_Image.setMinimumSize(QtCore.QSize(0, 0))
        self.Times_Image.setObjectName("Times_Image")
        self.horizontalLayout_15.addWidget(self.Times_Image)
        self.verticalLayout_14.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_14.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_11.addLayout(self.verticalLayout_14)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        self.verticalLayout_15.addLayout(self.horizontalLayout_9)
        self.RifePB_2 = QtWidgets.QProgressBar(self.Image)
        self.RifePB_2.setProperty("value", 0)
        self.RifePB_2.setObjectName("RifePB_2")
        self.verticalLayout_15.addWidget(self.RifePB_2)
        self.verticalTabWidget.addTab(self.Image, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.Settings)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.settingsGridLayout = QtWidgets.QGridLayout()
        self.settingsGridLayout.setObjectName("settingsGridLayout")
        self.SettingsMenus = QtWidgets.QListWidget(self.Settings)
        self.SettingsMenus.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SettingsMenus.setIconSize(QtCore.QSize(50, 40))
        self.SettingsMenus.setObjectName("SettingsMenus")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.SettingsMenus.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.SettingsMenus.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.SettingsMenus.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.SettingsMenus.addItem(item)
        self.settingsGridLayout.addWidget(self.SettingsMenus, 1, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_3.addLayout(self.verticalLayout_5, 1, 4, 1, 1)
        self.RenderOptionsFrame = QtWidgets.QFrame(self.Settings)
        self.RenderOptionsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RenderOptionsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RenderOptionsFrame.setObjectName("RenderOptionsFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.RenderOptionsFrame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.vramAmountHelpButton = QtWidgets.QPushButton(self.RenderOptionsFrame)
        self.vramAmountHelpButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/Rife-ESRGAN-Video-Settings - Help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vramAmountHelpButton.setIcon(icon)
        self.vramAmountHelpButton.setObjectName("vramAmountHelpButton")
        self.gridLayout_5.addWidget(self.vramAmountHelpButton, 2, 4, 1, 1)
        self.frameIncrementSpinBox = QtWidgets.QSpinBox(self.RenderOptionsFrame)
        self.frameIncrementSpinBox.setMinimum(10)
        self.frameIncrementSpinBox.setMaximum(10000)
        self.frameIncrementSpinBox.setObjectName("frameIncrementSpinBox")
        self.gridLayout_5.addWidget(self.frameIncrementSpinBox, 6, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.RenderOptionsFrame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 3, 3, 1, 1)
        self.renderTypeHelpButton = QtWidgets.QPushButton(self.RenderOptionsFrame)
        self.renderTypeHelpButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../.REAL-Video-Enhancer/icons/Rife-ESRGAN-Video-Settings - Help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.renderTypeHelpButton.setIcon(icon1)
        self.renderTypeHelpButton.setObjectName("renderTypeHelpButton")
        self.gridLayout_5.addWidget(self.renderTypeHelpButton, 4, 4, 1, 1)
        self.RenderPathLabel = QtWidgets.QLabel(self.RenderOptionsFrame)
        self.RenderPathLabel.setObjectName("RenderPathLabel")
        self.gridLayout_5.addWidget(self.RenderPathLabel, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.RenderOptionsFrame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 3, 1, 1)
        self.renderTypeCombo = QtWidgets.QComboBox(self.RenderOptionsFrame)
        self.renderTypeCombo.setObjectName("renderTypeCombo")
        self.renderTypeCombo.addItem("")
        self.renderTypeCombo.addItem("")
        self.gridLayout_5.addWidget(self.renderTypeCombo, 4, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.RenderOptionsFrame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 4, 3, 1, 1)
        self.imageComboBox = QtWidgets.QComboBox(self.RenderOptionsFrame)
        self.imageComboBox.setObjectName("imageComboBox")
        self.imageComboBox.addItem("")
        self.imageComboBox.addItem("")
        self.imageComboBox.addItem("")
        self.gridLayout_5.addWidget(self.imageComboBox, 3, 5, 1, 1)
        self.RenderDirButton = QtWidgets.QPushButton(self.RenderOptionsFrame)
        self.RenderDirButton.setObjectName("RenderDirButton")
        self.gridLayout_5.addWidget(self.RenderDirButton, 1, 5, 1, 1)
        self.imageHelpButton = QtWidgets.QPushButton(self.RenderOptionsFrame)
        self.imageHelpButton.setText("")
        self.imageHelpButton.setIcon(icon)
        self.imageHelpButton.setObjectName("imageHelpButton")
        self.gridLayout_5.addWidget(self.imageHelpButton, 3, 4, 1, 1)
        self.vramAmountSpinbox = QtWidgets.QSpinBox(self.RenderOptionsFrame)
        self.vramAmountSpinbox.setObjectName("vramAmountSpinbox")
        self.gridLayout_5.addWidget(self.vramAmountSpinbox, 2, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 7, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.RenderOptionsFrame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 6, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.RenderOptionsFrame)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 5, 3, 1, 1)
        self.frameIncrementsModeCombo = QtWidgets.QComboBox(self.RenderOptionsFrame)
        self.frameIncrementsModeCombo.setObjectName("frameIncrementsModeCombo")
        self.frameIncrementsModeCombo.addItem("")
        self.frameIncrementsModeCombo.addItem("")
        self.gridLayout_5.addWidget(self.frameIncrementsModeCombo, 5, 5, 1, 1)
        self.frameIncrementHelp = QtWidgets.QPushButton(self.RenderOptionsFrame)
        self.frameIncrementHelp.setText("")
        self.frameIncrementHelp.setIcon(icon1)
        self.frameIncrementHelp.setObjectName("frameIncrementHelp")
        self.gridLayout_5.addWidget(self.frameIncrementHelp, 5, 4, 1, 1)
        self.gridLayout_3.addWidget(self.RenderOptionsFrame, 1, 0, 1, 1)
        self.VideoOptionsFrame = QtWidgets.QFrame(self.Settings)
        self.VideoOptionsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VideoOptionsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VideoOptionsFrame.setMidLineWidth(0)
        self.VideoOptionsFrame.setObjectName("VideoOptionsFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.VideoOptionsFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.encoderHelpButton = QtWidgets.QPushButton(self.VideoOptionsFrame)
        self.encoderHelpButton.setText("")
        self.encoderHelpButton.setObjectName("encoderHelpButton")
        self.gridLayout_4.addWidget(self.encoderHelpButton, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.VideoOptionsFrame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 1, 1)
        self.VidQualityCombo = QtWidgets.QComboBox(self.VideoOptionsFrame)
        self.VidQualityCombo.setObjectName("VidQualityCombo")
        self.VidQualityCombo.addItem("")
        self.VidQualityCombo.addItem("")
        self.VidQualityCombo.addItem("")
        self.VidQualityCombo.addItem("")
        self.VidQualityCombo.addItem("")
        self.gridLayout_4.addWidget(self.VidQualityCombo, 0, 2, 1, 1)
        self.sceneChangeLineEdit = QtWidgets.QLineEdit(self.VideoOptionsFrame)
        self.sceneChangeLineEdit.setText("")
        self.sceneChangeLineEdit.setMaxLength(1)
        self.sceneChangeLineEdit.setObjectName("sceneChangeLineEdit")
        self.gridLayout_4.addWidget(self.sceneChangeLineEdit, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.VideoOptionsFrame)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.VideoOptionsFrame)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.EncoderCombo = QtWidgets.QComboBox(self.VideoOptionsFrame)
        self.EncoderCombo.setObjectName("EncoderCombo")
        self.EncoderCombo.addItem("")
        self.EncoderCombo.addItem("")
        self.gridLayout_4.addWidget(self.EncoderCombo, 3, 2, 1, 1)
        self.sceneChangeSensativityButton = QtWidgets.QPushButton(self.VideoOptionsFrame)
        self.sceneChangeSensativityButton.setText("")
        icon = QtGui.QIcon.fromTheme("dialog-information")
        self.sceneChangeSensativityButton.setIcon(icon)
        self.sceneChangeSensativityButton.setObjectName("sceneChangeSensativityButton")
        self.gridLayout_4.addWidget(self.sceneChangeSensativityButton, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.VideoOptionsFrame)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.sceneChangeDetectionCheckBox = QtWidgets.QCheckBox(self.VideoOptionsFrame)
        self.sceneChangeDetectionCheckBox.setTristate(False)
        self.sceneChangeDetectionCheckBox.setObjectName("sceneChangeDetectionCheckBox")
        self.gridLayout_4.addWidget(self.sceneChangeDetectionCheckBox, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.VideoOptionsFrame, 1, 3, 1, 1)
        self.GeneralOptionsFrame = QtWidgets.QFrame(self.Settings)
        self.GeneralOptionsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GeneralOptionsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GeneralOptionsFrame.setObjectName("GeneralOptionsFrame")
        self.formLayout = QtWidgets.QFormLayout(self.GeneralOptionsFrame)
        self.formLayout.setObjectName("formLayout")
        self.DiscordRPCBox = QtWidgets.QCheckBox(self.GeneralOptionsFrame)
        self.DiscordRPCBox.setObjectName("DiscordRPCBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DiscordRPCBox)
        self.OutputDirectoryButton = QtWidgets.QPushButton(self.GeneralOptionsFrame)
        self.OutputDirectoryButton.setObjectName("OutputDirectoryButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.OutputDirectoryButton)
        self.OutputDirectoryLabel = QtWidgets.QLabel(self.GeneralOptionsFrame)
        self.OutputDirectoryLabel.setObjectName("OutputDirectoryLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.OutputDirectoryLabel)
        self.resetSettingsButton = QtWidgets.QPushButton(self.GeneralOptionsFrame)
        self.resetSettingsButton.setObjectName("resetSettingsButton")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.resetSettingsButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.FieldRole, spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem9)
        self.label_8 = QtWidgets.QLabel(self.GeneralOptionsFrame)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.themeCombo = QtWidgets.QComboBox(self.GeneralOptionsFrame)
        self.themeCombo.setObjectName("themeCombo")
        self.themeCombo.addItem("")
        self.themeCombo.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.themeCombo)
        self.gridLayout_3.addWidget(self.GeneralOptionsFrame, 0, 0, 1, 1)
        self.InstallModelsFrame = QtWidgets.QFrame(self.Settings)
        self.InstallModelsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InstallModelsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InstallModelsFrame.setObjectName("InstallModelsFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.InstallModelsFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtWidgets.QLabel(self.InstallModelsFrame)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.InstallButton = QtWidgets.QPushButton(self.InstallModelsFrame)
        self.InstallButton.setObjectName("InstallButton")
        self.gridLayout.addWidget(self.InstallButton, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.InstallModelsFrame)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 0, 1, 1)
        self.installModelsProgressBar = QtWidgets.QProgressBar(self.InstallModelsFrame)
        self.installModelsProgressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.installModelsProgressBar.setProperty("value", 0)
        self.installModelsProgressBar.setTextVisible(False)
        self.installModelsProgressBar.setInvertedAppearance(False)
        self.installModelsProgressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.installModelsProgressBar.setObjectName("installModelsProgressBar")
        self.gridLayout.addWidget(self.installModelsProgressBar, 7, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Waifu2xCheckBox = QtWidgets.QCheckBox(self.InstallModelsFrame)
        self.Waifu2xCheckBox.setObjectName("Waifu2xCheckBox")
        self.gridLayout_6.addWidget(self.Waifu2xCheckBox, 6, 0, 1, 1)
        self.RealCUGANCheckBox = QtWidgets.QCheckBox(self.InstallModelsFrame)
        self.RealCUGANCheckBox.setEnabled(True)
        self.RealCUGANCheckBox.setObjectName("RealCUGANCheckBox")
        self.gridLayout_6.addWidget(self.RealCUGANCheckBox, 3, 0, 1, 1)
        self.RifeCheckBox = QtWidgets.QCheckBox(self.InstallModelsFrame)
        self.RifeCheckBox.setObjectName("RifeCheckBox")
        self.gridLayout_6.addWidget(self.RifeCheckBox, 4, 0, 1, 1)
        self.CainCheckBox = QtWidgets.QCheckBox(self.InstallModelsFrame)
        self.CainCheckBox.setEnabled(True)
        self.CainCheckBox.setObjectName("CainCheckBox")
        self.gridLayout_6.addWidget(self.CainCheckBox, 7, 0, 1, 1)
        self.RealESRGANCheckBox = QtWidgets.QCheckBox(self.InstallModelsFrame)
        self.RealESRGANCheckBox.setObjectName("RealESRGANCheckBox")
        self.gridLayout_6.addWidget(self.RealESRGANCheckBox, 1, 0, 1, 1)
        self.RifeSettings = QtWidgets.QPushButton(self.InstallModelsFrame)
        self.RifeSettings.setObjectName("RifeSettings")
        self.gridLayout_6.addWidget(self.RifeSettings, 4, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 4, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_19 = QtWidgets.QLabel(self.InstallModelsFrame)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_17.addWidget(self.label_19)
        self.defaultRifeModel = QtWidgets.QComboBox(self.InstallModelsFrame)
        self.defaultRifeModel.setObjectName("defaultRifeModel")
        self.horizontalLayout_17.addWidget(self.defaultRifeModel)
        self.gridLayout.addLayout(self.horizontalLayout_17, 1, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_20 = QtWidgets.QLabel(self.InstallModelsFrame)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_18.addWidget(self.label_20)
        self.ESRGANModelSelectButton = QtWidgets.QPushButton(self.InstallModelsFrame)
        self.ESRGANModelSelectButton.setObjectName("ESRGANModelSelectButton")
        self.horizontalLayout_18.addWidget(self.ESRGANModelSelectButton)
        self.gridLayout.addLayout(self.horizontalLayout_18, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.InstallModelsFrame, 0, 3, 1, 1)
        self.settingsGridLayout.addLayout(self.gridLayout_3, 1, 2, 1, 1)
        self.verticalLayout1.addLayout(self.settingsGridLayout)
        self.verticalTabWidget.addTab(self.Settings, "")
        self.gridLayout_2.addWidget(self.verticalTabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.verticalTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "REAL Video Enhancer"))
        self.QueueButton.setText(_translate("MainWindow", "Add to queue"))
        self.RifePause.setText(_translate("MainWindow", "Pause"))
        self.RifeResume.setText(_translate("MainWindow", "Resume"))
        self.processedPreview.setText(_translate("MainWindow", "Files Processed: "))
        self.ETAPreview.setText(_translate("MainWindow", "ETA: "))
        self.FPSPreview.setText(_translate("MainWindow", "FPS:"))
        self.RifeStart.setText(_translate("MainWindow", "Start"))
        self.Input_video_rife.setText(_translate("MainWindow", "Input Video"))
        self.Input_video_rife_url.setText(_translate("MainWindow", "Input Video URL"))
        self.Output_folder_rife.setText(_translate("MainWindow", "Output folder"))
        self.label_11.setText(_translate("MainWindow", "AI:"))
        self.label_12.setText(_translate("MainWindow", "Model:"))
        self.label_14.setText(_translate("MainWindow", "Times:"))
        self.Rife_Times.setItemText(0, _translate("MainWindow", "2X"))
        self.Rife_Times.setItemText(1, _translate("MainWindow", "4X"))
        self.Rife_Times.setItemText(2, _translate("MainWindow", "8X"))
        self.denoiseLevelLabel.setText(_translate("MainWindow", "Denoise level:"))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.Video), _translate("MainWindow", "Video"))
        self.RESPreview.setText(_translate("MainWindow", "RES: "))
        self.RifeStart_2.setText(_translate("MainWindow", "Start"))
        self.Input_Image.setText(_translate("MainWindow", "Input Image"))
        self.Input_video_rife_url_2.setText(_translate("MainWindow", "Input Image URL"))
        self.Output_folder_rife_2.setText(_translate("MainWindow", "Output folder"))
        self.label_15.setText(_translate("MainWindow", "AI:"))
        self.label_16.setText(_translate("MainWindow", "Model:"))
        self.label_17.setText(_translate("MainWindow", "Times:"))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.Image), _translate("MainWindow", "Image"))
        __sortingEnabled = self.SettingsMenus.isSortingEnabled()
        self.SettingsMenus.setSortingEnabled(False)
        item = self.SettingsMenus.item(0)
        item.setText(_translate("MainWindow", "General"))
        item = self.SettingsMenus.item(1)
        item.setText(_translate("MainWindow", "Render Options"))
        item = self.SettingsMenus.item(2)
        item.setText(_translate("MainWindow", "Video Options"))
        item = self.SettingsMenus.item(3)
        item.setText(_translate("MainWindow", "Manage Models"))
        self.SettingsMenus.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "Image Type"))
        self.RenderPathLabel.setText(_translate("MainWindow", "Render Directory:"))
        self.label_5.setText(_translate("MainWindow", "VRAM amount"))
        self.renderTypeCombo.setItemText(0, _translate("MainWindow", "Classic"))
        self.renderTypeCombo.setItemText(1, _translate("MainWindow", "Optimized"))
        self.label_6.setText(_translate("MainWindow", "Render Type"))
        self.imageComboBox.setItemText(0, _translate("MainWindow", ".jpg"))
        self.imageComboBox.setItemText(1, _translate("MainWindow", ".png"))
        self.imageComboBox.setItemText(2, _translate("MainWindow", ".webp"))
        self.RenderDirButton.setText(_translate("MainWindow", "Render Directory"))
        self.vramAmountSpinbox.setSuffix(_translate("MainWindow", " GB"))
        self.label_7.setText(_translate("MainWindow", "Frame Increments"))
        self.label_9.setText(_translate("MainWindow", "Frame Increments mode"))
        self.frameIncrementsModeCombo.setItemText(0, _translate("MainWindow", "Automatic"))
        self.frameIncrementsModeCombo.setItemText(1, _translate("MainWindow", "Manual"))
        self.VideoOptionsFrame.setProperty("visable", _translate("MainWindow", "false"))
        self.label_2.setText(_translate("MainWindow", "Encoder"))
        self.VidQualityCombo.setItemText(0, _translate("MainWindow", "Low"))
        self.VidQualityCombo.setItemText(1, _translate("MainWindow", "Medium"))
        self.VidQualityCombo.setItemText(2, _translate("MainWindow", "High"))
        self.VidQualityCombo.setItemText(3, _translate("MainWindow", "Very High"))
        self.VidQualityCombo.setItemText(4, _translate("MainWindow", "Lossless"))
        self.label_3.setText(_translate("MainWindow", "Scene Change Detection Sensativity"))
        self.label.setText(_translate("MainWindow", "Video Output Quality"))
        self.EncoderCombo.setItemText(0, _translate("MainWindow", ".264"))
        self.EncoderCombo.setItemText(1, _translate("MainWindow", ".265"))
        self.sceneChangeDetectionCheckBox.setText(_translate("MainWindow", "Scene Change Detection"))
        self.DiscordRPCBox.setText(_translate("MainWindow", "Discord Rich Presence"))
        self.OutputDirectoryButton.setText(_translate("MainWindow", "Output Directory"))
        self.OutputDirectoryLabel.setText(_translate("MainWindow", "TextLabel"))
        self.resetSettingsButton.setText(_translate("MainWindow", "Reset Settings"))
        self.label_8.setText(_translate("MainWindow", "Theme"))
        self.themeCombo.setItemText(0, _translate("MainWindow", "Dark"))
        self.themeCombo.setItemText(1, _translate("MainWindow", "Flashbang"))
        self.label_13.setText(_translate("MainWindow", "Available Models:"))
        self.InstallButton.setText(_translate("MainWindow", "Install/Remove"))
        self.label_18.setText(_translate("MainWindow", "Model Defaults"))
        self.Waifu2xCheckBox.setText(_translate("MainWindow", "Waifu2X"))
        self.RealCUGANCheckBox.setText(_translate("MainWindow", "RealCUGAN"))
        self.RifeCheckBox.setText(_translate("MainWindow", "Rife"))
        self.CainCheckBox.setText(_translate("MainWindow", "IFRNET"))
        self.RealESRGANCheckBox.setText(_translate("MainWindow", "RealESRGAN"))
        self.RifeSettings.setText(_translate("MainWindow", "Settings"))
        self.label_19.setText(_translate("MainWindow", "Default Rife Model:"))
        self.label_20.setText(_translate("MainWindow", "Import ESRGAN Model"))
        self.ESRGANModelSelectButton.setText(_translate("MainWindow", "Select Bin/Param file"))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.Settings), _translate("MainWindow", "Settings"))
