[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.3",
    "numpy>=2.4.6",
    "opencv-python>=4.13.0.92",
    "platformdirs>=4.10.0",
    "pydantic>=2.13.4",
    "ruff>=0.15.16",
    "uvicorn>=0.49.0",
]

[dependency-groups]
dev = [
    "torch>=2.12.0",
    "torchvision>=0.27.0",
]
