def styleSheet():
    return (
        "\n"
        "\n"
        "QMainWindow {\n"
        "   color:black;\n"
        "   background-color:black;\n"
        "border:1px;\n"
        "}\n"
        "QLabel{\n"
        "	color: #fff;\n"
        "}\n"
        "QLineEdit{\n"
        "color: #fff;\n"
        "}\n"
        "#centralwidget{\n"
        "	background-color:#1f232a;\n"
        "}\n"
        "#leftMenuSubContainer{\n"
        "	background-color:#16191d;\n"
        "   border-radius: 30px;\n"
        "}\n"
        "#bottomMenuSubContainer{\n"
        "	background-color:#16191d;\n"
        "   border-radius: 30px;\n"
        "}\n"
        "\n"
        "QProgressBar{\n"
        "    background-color:#2c313c;\n"
        "	text-align:left;\n"
        "	padding:5px 10px;\n"
        "	border-radius: 10px;\n"
        "\n"
        "}\n"
        " QProgressBar::chunk {\n"
        "     background-color:white;\n"
        "	text-align:left;\n"
        "	border-radius: 10px;\n"
        " }\n"
        "QStackedWidget{\n"
        "	background-color:#16191d;\n"
        "	text-align:left;\n"
        "	padding:5px 10px;\n"
        "	border-radius: 25px;\n"
        "}\n"
        "QPushButton{\n"
        "    background-color:#2c313c;\n"
        "	text-align:left;\n"
        "	padding:5px 10px;\n"
        "	border-radius: 10px;\n"
        "    color: #fff;\n"
        "}\n"
        "QPushButton:checked{\n"
        "	background-color:#676e7b;\n"
        "}\n"
        "QPushButton:ho"
        "ver{\n"
        "	background-color:#343b47;\n"
        "}\n"
        "\n"
        ""
    )
