# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/getModels/SelectModels.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(973, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 8, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rife = QtWidgets.QCheckBox(self.centralwidget)
        self.rife.setObjectName("rife")
        self.verticalLayout.addWidget(self.rife)
        self.rifeanime = QtWidgets.QCheckBox(self.centralwidget)
        self.rifeanime.setObjectName("rifeanime")
        self.verticalLayout.addWidget(self.rifeanime)
        self.rifehd = QtWidgets.QCheckBox(self.centralwidget)
        self.rifehd.setObjectName("rifehd")
        self.verticalLayout.addWidget(self.rifehd)
        self.rifeuhd = QtWidgets.QCheckBox(self.centralwidget)
        self.rifeuhd.setObjectName("rifeuhd")
        self.verticalLayout.addWidget(self.rifeuhd)
        self.rife2 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife2.setObjectName("rife2")
        self.verticalLayout.addWidget(self.rife2)
        self.rife23 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife23.setObjectName("rife23")
        self.verticalLayout.addWidget(self.rife23)
        self.rife24 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife24.setObjectName("rife24")
        self.verticalLayout.addWidget(self.rife24)
        self.rife30 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife30.setObjectName("rife30")
        self.verticalLayout.addWidget(self.rife30)
        self.rife31 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife31.setObjectName("rife31")
        self.verticalLayout.addWidget(self.rife31)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.rife4 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife4.setObjectName("rife4")
        self.verticalLayout_6.addWidget(self.rife4)
        self.rife41 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife41.setObjectName("rife41")
        self.verticalLayout_6.addWidget(self.rife41)
        self.rife42 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife42.setObjectName("rife42")
        self.verticalLayout_6.addWidget(self.rife42)
        self.rife43 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife43.setObjectName("rife43")
        self.verticalLayout_6.addWidget(self.rife43)
        self.rife44 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife44.setObjectName("rife44")
        self.verticalLayout_6.addWidget(self.rife44)
        self.rife45 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife45.setObjectName("rife45")
        self.verticalLayout_6.addWidget(self.rife45)
        self.rife46 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife46.setChecked(False)
        self.rife46.setObjectName("rife46")
        self.verticalLayout_6.addWidget(self.rife46)
        self.rife47 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife47.setObjectName("rife47")
        self.verticalLayout_6.addWidget(self.rife47)
        self.rife48 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife48.setObjectName("rife48")
        self.verticalLayout_6.addWidget(self.rife48)
        self.rife49 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife49.setObjectName("rife49")
        self.verticalLayout_6.addWidget(self.rife49)
        self.rife410 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife410.setObjectName("rife410")
        self.verticalLayout_6.addWidget(self.rife410)
        self.rife411 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife411.setObjectName("rife411")
        self.verticalLayout_6.addWidget(self.rife411)
        self.rife412 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife412.setObjectName("rife412")
        self.verticalLayout_6.addWidget(self.rife412)
        self.rife413 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife413.setObjectName("rife413")
        self.verticalLayout_6.addWidget(self.rife413)
        self.rife414 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife414.setObjectName("rife414")
        self.verticalLayout_6.addWidget(self.rife414)
        self.rife415 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife415.setObjectName("rife415")
        self.verticalLayout_6.addWidget(self.rife415)
        self.rife417 = QtWidgets.QCheckBox(self.centralwidget)
        self.rife417.setObjectName("rife417")
        self.verticalLayout_6.addWidget(self.rife417)
        self.gridLayout.addLayout(self.verticalLayout_6, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 7, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setObjectName("next")
        self.verticalLayout_5.addWidget(self.next)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 10, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 9, 1, 1)
        self.vert_lay = QtWidgets.QVBoxLayout()
        self.vert_lay.setObjectName("vert_lay")
        self.custom_models = QtWidgets.QVBoxLayout()
        self.custom_models.setObjectName("custom_models")
        self.vert_lay.addLayout(self.custom_models)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vert_lay.addItem(spacerItem7)
        self.gridLayout.addLayout(self.vert_lay, 1, 8, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 1, 4, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rife412lite = QtWidgets.QCheckBox(self.centralwidget)
        self.rife412lite.setObjectName("rife412lite")
        self.verticalLayout_3.addWidget(self.rife412lite)
        self.rife413lite = QtWidgets.QCheckBox(self.centralwidget)
        self.rife413lite.setObjectName("rife413lite")
        self.verticalLayout_3.addWidget(self.rife413lite)
        self.rife414lite = QtWidgets.QCheckBox(self.centralwidget)
        self.rife414lite.setEnabled(False)
        self.rife414lite.setObjectName("rife414lite")
        self.verticalLayout_3.addWidget(self.rife414lite)
        self.rife416lite = QtWidgets.QCheckBox(self.centralwidget)
        self.rife416lite.setObjectName("rife416lite")
        self.verticalLayout_3.addWidget(self.rife416lite)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 6, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "REAL Video Enhancer"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:700;\">Select Rife Models to Download:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Custom Models:"))
        self.rife.setText(_translate("MainWindow", "Rife "))
        self.rifeanime.setText(_translate("MainWindow", "Rife-Anime "))
        self.rifehd.setText(_translate("MainWindow", "Rife-HD "))
        self.rifeuhd.setText(_translate("MainWindow", "Rife-UHD "))
        self.rife2.setText(_translate("MainWindow", "Rife-V2 "))
        self.rife23.setText(_translate("MainWindow", "Rife-V2.3 "))
        self.rife24.setText(_translate("MainWindow", "Rife-V2.4"))
        self.rife30.setText(_translate("MainWindow", "Rife-V3.0"))
        self.rife31.setText(_translate("MainWindow", "Rife-V3.1"))
        self.rife4.setText(_translate("MainWindow", "Rife-V4"))
        self.rife41.setText(_translate("MainWindow", "Rife-V4.1"))
        self.rife42.setText(_translate("MainWindow", "Rife-V4.2"))
        self.rife43.setText(_translate("MainWindow", "Rife-V4.3"))
        self.rife44.setText(_translate("MainWindow", "Rife-V4.4"))
        self.rife45.setText(_translate("MainWindow", "Rife-V4.5"))
        self.rife46.setText(_translate("MainWindow", "Rife-V4.6 "))
        self.rife47.setText(_translate("MainWindow", "Rife-V4.7"))
        self.rife48.setText(_translate("MainWindow", "Rife-V4.8 "))
        self.rife49.setText(_translate("MainWindow", "Rife-V4.9 "))
        self.rife410.setText(_translate("MainWindow", "Rife-V4.10"))
        self.rife411.setText(_translate("MainWindow", "Rife-V4.11"))
        self.rife412.setText(_translate("MainWindow", "Rife-V4.12"))
        self.rife413.setText(_translate("MainWindow", "Rife-V4.13"))
        self.rife414.setText(_translate("MainWindow", "Rife-V4.14"))
        self.rife415.setText(_translate("MainWindow", "Rife-V4.15"))
        self.rife417.setText(_translate("MainWindow", "Rife-V4.17"))
        self.next.setText(_translate("MainWindow", "Next"))
        self.label_2.setText(_translate("MainWindow", "Recommended models  (2X), (4X), (8X)"))
        self.label_4.setText(_translate("MainWindow", "Old Models (2X)"))
        self.rife412lite.setText(_translate("MainWindow", "Rife-V4.12-lite"))
        self.rife413lite.setText(_translate("MainWindow", "Rife-V4.13-lite"))
        self.rife414lite.setText(_translate("MainWindow", "Rife-V4.14-lite"))
        self.rife416lite.setText(_translate("MainWindow", "Rife-V4.16-lite"))
        self.label_5.setText(_translate("MainWindow", "Lite models (2x), (4x), (8x))"))
